version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      DB_URL: mysql+pymysql://root:password@mysql:3306/db
    command: "uvicorn api.main:app --port 8000 --host 0.0.0.0"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"

  mysql:
    container_name: technical-assessment-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    image: "mysql:8.0"
    ports:
      - "3306:3306"
